version: '3'
name: jx-erta-localdev

services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: ./dev.Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #   - "./client/:/app"
  #   env_file:
  #     - "client/.env"
  #   entrypoint: 
  #   - "/bin/sh"
  #   - "-c"
  #   - "npm install && npm run dev"
  #   network_mode: bridge
  #   restart: always

  server:
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    ports:
      - "4000:4000"
    volumes:
    - "./server/:/app"
    env_file:
      - "server/.env"
    entrypoint: 
    - "/bin/sh"
    - "-c"
    - "npm install && npm run start"
    links:
      - database:database
    network_mode: bridge
    restart: always

  database:
    image: postgres:15.2
    volumes:
    - "./database/data:/var/lib/postgresql/data"
    env_file:
      - "database/.env"
    ports:
      - "5432:5432"
    network_mode: bridge
    restart: always

# docker compose -f docker-compose.localdev.yaml up -d --build